//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestureRecognition.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GestureRecognitionLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GestureRecognitionLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestureRecognition.Localization.GestureRecognitionLocalization", typeof(GestureRecognitionLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутрішні контури.
        /// </summary>
        internal static string AreContoursExternalCheckBoxText {
            get {
                return ResourceManager.GetString("AreContoursExternalCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найбільший контур.
        /// </summary>
        internal static string BiggestContourBoundingRectangleLabelText {
            get {
                return ResourceManager.GetString("BiggestContourBoundingRectangleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бінаризація.
        /// </summary>
        internal static string BinaryImageLabelText {
            get {
                return ResourceManager.GetString("BinaryImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поріг бінаризації.
        /// </summary>
        internal static string BinaryImageThresholdTrackBarLabelText {
            get {
                return ResourceManager.GetString("BinaryImageThresholdTrackBarLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захопити зображення.
        /// </summary>
        internal static string CaptureImageToRecognizeButtonText {
            get {
                return ResourceManager.GetString("CaptureImageToRecognizeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виділені контури.
        /// </summary>
        internal static string ContourBoundingRectanglesLabelText {
            get {
                return ResourceManager.GetString("ContourBoundingRectanglesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контури.
        /// </summary>
        internal static string ContoursLabelText {
            get {
                return ResourceManager.GetString("ContoursLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінальне зображення.
        /// </summary>
        internal static string DataImageLabelText {
            get {
                return ResourceManager.GetString("DataImageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер жесту.
        /// </summary>
        internal static string GestureNumberLabelText {
            get {
                return ResourceManager.GetString("GestureNumberLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система розпізнавання жестів.
        /// </summary>
        internal static string HandGesturesRecognitionFormTitleText {
            get {
                return ResourceManager.GetString("HandGesturesRecognitionFormTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення для розпізнавання.
        /// </summary>
        internal static string ImageToRecognizeLabelText {
            get {
                return ResourceManager.GetString("ImageToRecognizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація.
        /// </summary>
        internal static string InfoLabelText {
            get {
                return ResourceManager.GetString("InfoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string OptionsGroupBoxText {
            get {
                return ResourceManager.GetString("OptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування розпізнавання.
        /// </summary>
        internal static string RecognitionOptionsGroupBoxText {
            get {
                return ResourceManager.GetString("RecognitionOptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат розпізнавання.
        /// </summary>
        internal static string RecognitionResultLabelText {
            get {
                return ResourceManager.GetString("RecognitionResultLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпізнати жест.
        /// </summary>
        internal static string RecognizeImageButtonText {
            get {
                return ResourceManager.GetString("RecognizeImageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадратний контур.
        /// </summary>
        internal static string SquaredBiggestContourBoundingRectangleLabel {
            get {
                return ResourceManager.GetString("SquaredBiggestContourBoundingRectangleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати навчання.
        /// </summary>
        internal static string StartTrainingButtonText {
            get {
                return ResourceManager.GetString("StartTrainingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зупинити навчання.
        /// </summary>
        internal static string StopTrainingButtonText {
            get {
                return ResourceManager.GetString("StopTrainingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування навчання мережі.
        /// </summary>
        internal static string TrainingOptionsGroupBoxText {
            get {
                return ResourceManager.GetString("TrainingOptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригінальне відео.
        /// </summary>
        internal static string VideoCaptureLabelText {
            get {
                return ResourceManager.GetString("VideoCaptureLabelText", resourceCulture);
            }
        }
    }
}
